### ISSUE TITLE
Make the Navbar align with the elements below

### ISSUE THREAD

**Issue by hubertle43100** [hubertle43100/minimal-ecommerce#34]
### It is offset when resizing the screen 

![Screenshot 2024-02-21 at 12 39 31 PM](https://github.com/hubertle43100/minimal-ecommerce/assets/56861838/e2baa3a8-b237-4b73-914d-991ceb53bc15)

**Comment by Elham-EN** [comment]
Hi @hubertle43100, I would straight like to work on the UI and can you assign me?
